version: "3"
services:
  node_app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
